common:
  msg_source: 1                                         #0: not use Lidar
                                                        #1: packet message comes from online Lidar
                                                        #2: packet message comes from ROS or ROS2
                                                        #3: packet message comes from Pcap file
  send_packet_ros: false                                #true: Send packets through ROS or ROS2(Used to record packet)
  send_point_cloud_ros: true                            #true: Send point cloud through ROS or ROS2
lidar:
  - driver:
      lidar_type: RS16            #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: rslidar           #Frame id of message
      msop_port: 6699              #Msop port of lidar
      difop_port: 7788             #Difop port of lidar
      start_angle: 0 #273 #271               #Start angle of point cloud
      end_angle: 360 #177.5 #178.5              #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 150            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp
      # x: 0.0
      # y: 0.0
      # z: 0.0
      # roll: 3.14
      # pitch: 3.14
      # yaw: -1.57                                      
    ros:
      ros_recv_packet_topic: /center/rslidar_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /center/rslidar_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /center/rslidar_points      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60024                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60024                     #Port number which the point cloud will be send to
      msop_recv_port: 60025                            #Port number used for receiving lidar msop packets
      msop_send_port: 60025                            #Port number which the msop packets will be send to 
      difop_recv_port: 60026                           #Port number used for receiving lidar difop packets
      difop_send_port: 60026                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 127.0.0.1                   #Ip address which the point cloud will be send to 
      packet_send_ip: 127.0.0.1                        #Ip address which the lidar packets will be send to