/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv2rgb" #mjpeg2rgb # see usb_cam/supported_formats for list of supported formats yuyv2rgb
      image_width: 160 #1280 #800 #640 #160
      image_height: 90 #720 #448 #480 #90
      camera_name: "logi_camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml" #"package://usb_cam/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1
