amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 25.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    set_initial_pose: True
    initial_pose.x: 0.0
    initial_pose.y: 0.0
    initial_pose.yaw: 0.0


bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    transform_tolerance: 0.1
    bt_loop_duration: 10
    default_server_timeout: 10
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_smooth_path_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_assisted_teleop_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_drive_on_heading_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_globally_updated_goal_condition_bt_node
    - nav2_is_path_valid_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_truncate_path_local_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_path_expiring_timer_condition
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_goal_updated_controller_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node
    - nav2_controller_cancel_bt_node
    - nav2_path_longer_on_approach_bt_node
    - nav2_wait_cancel_bt_node
    - nav2_spin_cancel_bt_node
    - nav2_back_up_cancel_bt_node
    - nav2_assisted_teleop_cancel_bt_node
    - nav2_drive_on_heading_cancel_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    odom_topic: /odom
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    speed_limit_topic: "/speed_limit"
    progress_checker_plugin: "progress_checker"
    # controller_plugin_types: ["teb_local_planner::TebLocalPlannerROS"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.5
      max_vel_y: 0.0
      max_vel_theta: 0.05
      min_speed_xy: 0.0
      max_speed_xy: 0.5
      min_speed_theta: 0.0
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 2.5 #2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5 #-2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 40
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05 #0.05
      angular_granularity: 0.05 #0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25 #0.25
      trans_stopped_velocity: 0.25 #0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02 #0.02
      ObstacleFootprint.scale: 1.0
      PathAlign.scale: 32.0 #32.0
      PathAlign.forward_point_distance: 0.325 #0.1
      GoalAlign.scale: 24.0 #24.0
      GoalAlign.forward_point_distance: 0.325 #0.1
      PathDist.scale: 32.0 #32.0
      GoalDist.scale: 24.0 #24.0
      RotateToGoal.scale: 32.0 #32.0
      RotateToGoal.slowing_factor: 5.0 #5.0
      RotateToGoal.lookahead_time: -1.0

    # # TEB parameters
    # FollowPath:
    #   plugin: "teb_local_planner::TebLocalPlannerROS"
    #   # footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    #   #   type: "polygon"
    #   #   vertices: "[[-0.3,-0.275], [0.3,-0.275], [0.3,0.275], [-0.3,0.275]]"

    #   footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    #     type: "circular"
    #     radius: 0.3

    #   # // Trajectory
    #   teb_autoresize: True
    #   dt_ref: 0.3
    #   dt_hysteresis: 0.1
    #   min_samples: 3
    #   max_samples: 20      
    #   global_plan_overwrite_orientation: true
    #   allow_init_with_backwards_motion: true #(this is only recommended if the robot is equipped with rear sensors)
    #   global_plan_viapoint_sep: 1.0     
    #   # via_points_ordered: true
    #   max_global_plan_lookahead_dist: 1.0  
    #   # global_plan_prune_distance: 1.0
    #   # exact_arc_length: true
    #   feasibility_check_no_poses: 5
    #   publish_feedback: true
    #   control_look_ahead_poses: 5


    # # Robot
    #   max_vel_x: 1.0
    #   max_vel_x_backwards: 0.125
    #   max_vel_theta: 0.125
    #   acc_lim_x: 0.5
    #   acc_lim_theta: 0.5
    #   # min_turning_radius: 0.0
    #   is_footprint_dynamic: true

    # # GoalTolerance
    #   xy_goal_tolerance: 0.3
    #   yaw_goal_tolerance: 0.3
    #   free_goal_vel: false 

    # # Obstacles
    #   min_obstacle_dist: 0.3    
    #   inflation_dist: 0.7
    #   dynamic_obstacle_inflation_dist: 0.6
    #   # include_dynamic_obstacles: true
    #   include_costmap_obstacles: true
    #   costmap_obstacles_behind_robot_dist: 2.0
    #   obstacle_poses_affected: 25
    #   costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
    #   costmap_converter_spin_thread: true
    #   costmap_converter_rate: 5

    # # Optimization
    #   # no_inner_iterations: 5
    #   # no_outer_iterations: 4
    #   optimization_activate: true
    #   weight_max_vel_x: 2.0
    #   weight_max_vel_theta: 2.0
    #   weight_acc_lim_x: 1.0
    #   weight_acc_lim_theta: 2.0
    #   weight_kinematics_nh: 2000.0
    #   weight_kinematics_forward_drive: 10000.0
    #   weight_obstacle: 1.0
    #   weight_inflation: 0.9
    #   # weight_dynamic_obstacle: 30.0
    #   # weight_dynamic_obstacle_inflation: 0.1
    #   weight_viapoint: 10.0
    #   penalty_epsilon: 0.02

    # # Homotopy Class Planner
    #   enable_homotopy_class_planning: false
    #   enable_multithreading: false
    #   max_number_classes: 5
    #   selection_cost_hysteresis: 1.0
    #   # selection_obst_cost_scale: 100.0
    #   selection_viapoint_cost_scale: 1.0
    #   roadmap_graph_no_samples: 15
    #   roadmap_graph_area_width: 6.0
    #   roadmap_graph_area_length_scale: 1.0
    #   h_signature_prescaler: 0.6
    #   h_signature_threshold: 0.1
    #   obstacle_keypoint_offset: 0.1
    #   obstacle_heading_threshold: 0.45 
    #   visualize_hc_graph: true

costmap_converter:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 8
      height: 8
      resolution: 0.05
      robot_radius: 0.4
      # footprint: "[[-0.3,-0.275], [0.3,-0.275], [0.3,0.275], [-0.3,0.275]]"
      plugins: ["voxel_layer", "inflation_layer"]     
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.9 #0.55
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 4.0 #3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 3.5 #2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      always_send_full_costmap: True 

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.4
      # footprint: "[[-0.3,-0.275], [0.3,-0.275], [0.3,0.275], [-0.3,0.275]]"
      resolution: 0.05
      track_unknown_space: true
      lethal_cost_threshold: 100
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      # UNCOMMENT THIS LINE BELOW FOR KEEPOUT DEMO
      # filters: ["keepout_filter", "inflation_layer"]  
      filters: ["speed_filter"]    
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 4.0 #3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 3.5 #2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0 #3.0
        inflation_radius: 0.9 #0.55
      speed_filter:
        plugin: "nav2_costmap_2d::SpeedFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
        speed_limit_topic: "/speed_limit"        
      always_send_full_costmap: True
      # UNCOMMENT NEXT 4 LINES HERE FOR KEEPOUT
      # keepout_filter:
      #   plugin: "nav2_costmap_2d::KeepoutFilter"
      #   enabled: True
      #   filter_info_topic: "/costmap_filter_info"  
      #   transform_tolerance: 0.3    

# UNCOMMENT NEXT 15 LINES HERE FOR KEEPOUT
# costmap_filter_info_server:
#   ros__parameters:
#     use_sim_time: true
#     type: 0
#     filter_info_topic: "/costmap_filter_info"
#     mask_topic: "/keepout_filter_mask"
#     base: 0.0
#     multiplier: 1.0

# filter_mask_server:
#   ros__parameters:
#     use_sim_time: true
#     frame_id: "map"
#     topic_name: "/keepout_filter_mask"
#     yaml_filename: "/home/wheelchair001/agv_ws/maps/lanes.yaml"

map_server:
  ros__parameters:
    use_sim_time: False
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

# planner_server:
#   ros__parameters:
#     expected_planner_frequency: 20.0
#     use_sim_time: False
#     #plugins: ["GridBased"]
#     planner_plugins: ["GridBased"]
#     GridBased:
#       plugin: "nav2_straightline_planner/StraightLine"
#       interpolation_resolution: 0.1

# planner_server:
#   ros__parameters:
#     expected_planner_frequency: 20.0
#     use_sim_time: False
#     planner_plugins: ["GridBased"]
#     GridBased:
#       plugin: "nav2_theta_star_planner/ThetaStarPlanner"
#       how_many_corners: 8
#       w_euc_cost: 1.0
#       w_traversal_cost: 2.0
#       w_heuristic_cost: 1.0

smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    # local_costmap_topic: local_costmap/costmap_raw
    # local_footprint_topic: local_costmap/published_footprint
    # global_costmap_topic: global_costmap/costmap_raw
    # global_footprint_topic: global_costmap/published_footprint    
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint    
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: odom
    # local_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 1.2
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.09
    min_rotational_vel: 0.05
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 0

# velocity_smoother:
#   ros__parameters:
#     use_sim_time: False
#     smoothing_frequency: 20.0
#     scale_velocities: False
#     feedback: "OPEN_LOOP"
#     max_velocity: [0.2, 0.0, 0.12]
#     min_velocity: [-0.2, 0.0, -0.12]
#     max_accel: [2.5, 0.0, 3.2]
#     max_decel: [-2.5, 0.0, -3.2]
#     odom_topic: "odom"
#     odom_duration: 0.1
#     deadband_velocity: [0.0, 0.0, 0.0]
#     velocity_timeout: 1.0

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 0.1396263402] #0.1396263402 0.1570796327
    min_velocity: [-0.5, 0.0, -0.1396263402]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0